---
title: 'Pediatric clinical trials: Prepare trial data for analysis'
author: "Stylianos Serghiou"
date: '`r format(Sys.time(), "%d/%m/%Y")`'
output:
  prettydoc::html_pretty:
    # no code_folding available
    theme: hpstr      # or: architect; https://github.com/yixuan/prettydoc
    highlight: github # or: vignette
    toc: TRUE         # no toc_float available
    df_print: kable   # obviates %>% kable; does not replace styling though
  tufte::tufte_handout: default
  pdf_document:
    highlight: tango
    df_print: kable
    latex_engine: pdflatex
    keep_tex: yes
  rmdformats::readthedown:
    highlight: kate
    df_print: kable    # obviates %>% kable; does not replace styling though
    code_folding: hide # or: show; (comment out to not give option)
  tufte::tufte_html: 
    toc: TRUE
  epuRate::epurate:
    df_print: kable
    toc: yes
  html_document:
    highlight: tango
    theme: sandstone
    df_print: kable
    toc: yes
    toc_depth: 2
    toc_float: yes
    css: "path_to_custom.css"
header-includes:
- \DeclareUnicodeCharacter{3B8}{~}
- \DeclareUnicodeCharacter{3B1}{~}
- \DeclareUnicodeCharacter{3B2}{~}
- \DeclareUnicodeCharacter{223C}{~}
- \DeclareUnicodeCharacter{2264}{~}
- \DeclareUnicodeCharacter{2265}{~}
- \DeclareUnicodeCharacter{2581}{~}
- \DeclareUnicodeCharacter{2582}{~}
- \DeclareUnicodeCharacter{2583}{~}
- \DeclareUnicodeCharacter{2585}{~}
- \DeclareUnicodeCharacter{2586}{~}
- \DeclareUnicodeCharacter{2587}{~} 
- \DeclareUnicodeCharacter{FB00}{~} 
- \usepackage{graphicx}
editor_options: 
  chunk_output_type: inline
---

<style>
p {

text-align: justify;
text-justify: interword;
padding: 0 0 0.5em 0

}
</style>

```{r setup, include=FALSE}
# Load packages
library(knitr)
library(rmdformats)
library(kableExtra)
library(ggplot2)
library(magrittr)



######### knitr

# Define chunk options
opts_chunk$set(
  echo = T,
  cache = F,  # if TRUE, no need to rerun chunks
  # cache.lazy = TRUE,  # use with big objects (>1 GB)
  cache.comments = F,  # do not rebuild if comments change
  tidy = F,  # can play with this
  warning = F, 
  message = F,
  comment = NA,
  fig.align = "center",
  fig.width = 7,
  fig.path = "Figs/",  # export all figures to dir Figs
  linewidth = 91,
  width = 75
)


# Initiatialize hook
hook_output = knit_hooks$get("output")


# Hook to wrap output text when it exceeds 'n' using linewidth
knit_hooks$set(output = function(x, options) {
  
  if (!is.null(n <- options$linewidth)) {
    x = knitr:::split_lines(x)
    
    # wrap lines wider than 'n' 
    if (any(nchar(x) > n)) 
      x <- strwrap(x, width = n)
      x <- paste(x, collapse = "\n")
  }
  hook_output(x, options)
})


# Times a chunk and prints the time it took to run it under the chunk
# To time a chunk, include in the chunk options: {r my_chunk, timeit=TRUE}
knitr::knit_hooks$set(timeit = local({
  now = NULL
  function(before, options) {
    if (before) {
      now <<- Sys.time()
    } else {
      res = difftime(Sys.time(), now)
      now <<- NULL
      # use options$label if you want the chunk label as well
      paste('Time for this code chunk:', as.character(res))
    }
  }})
)


# For more knitr options visit: https://yihui.name/knitr/options/
# and his github page: https://github.com/yihui/knitr-examples



######### kableExtra

options(knitr.kable.NA = ''  # replace NAs in tables with blank
        , digits = 3)          # round digits (doesn't work without this here!)

## Example use
# data.frame(x = c(1,2,3), y = c(4,5,6), z = c(7,8,9)) %>% 
#   kable(booktabs = T) %>% kable_styling()

# Function to simplify table styling
sable <- function(tab, escape = T, full_width = F, drop = F, font_size = 12) {
  if (drop) {
    tab %>%
      kable(escape = escape, booktabs = T) %>%
      collapse_rows(valign = "top") %>% 
      kable_styling("striped", 
                    position = "center", 
                    full_width = full_width, 
                    font_size = font_size)
  } else {
    tab %>%
      kable(escape = escape, booktabs = T) %>%
      kable_styling("striped", 
                    position = "center", 
                    full_width = full_width,
                    font_size = font_size)
  }
}

## Guidelines
# No longer need to define options(knitr.table.format = "html"). It is now automatically done as soon as you load kableExtra
# No need to run kable() every time - done automatically as soon as you load kableExtra
# Loading kableExtra nullifies any styling applied by df_table: kable in the preamble - if you are content with standard formatting, DO NOT load kableExtra



#########  ggplot2

# Set up preferred theme in ggplot2
my_theme <- 
  # this and theme_minimal() are my favorite
  theme_light() +  
  theme(
    axis.ticks = element_blank(),
    axis.title = element_text(face = "bold"),
    axis.title.x = element_text(margin = margin(t = 20)),
    axis.title.y  = element_text(margin = margin(r = 3)),
    legend.key = element_rect(colour = NA, fill = NA),  # Avoid borders
    panel.border = element_blank(), 
    text = element_text(color = "grey20"),
    title = element_text(face = "bold")
  )

# Make the above theme the default theme
original_theme <- theme_set(my_theme)

# Use ggsave to save plots after plotting - this reduces size dramatically



######### Live preview

# Preview the HTML without having to re-knit
# https://www.r-bloggers.com/create-r-markdown-reports-and-presentations-even-better-with-these-3-practical-tips/amp/

# xaringan::infinite_moon_reader()




######### Tabbed sections

# You can organize content using tabs by applying the .tabset class attribute to headers within a document. This will cause all sub-headers of the header with the .tabset attribute to appear within tabs rather than as standalone sections. For example:

## Quarterly Results {.tabset}

### By Product



######### Update package

# To update the package use:
# Replace ~/serghiouTemplates/inst/rmarkdown/templates/report/skeleton.rmd
# library(devtools); setwd("/Users/Stelios/"); install("serghiouTemplates")
```


# Setup {.tabset}

<!-- Chunk called setup_2 to avoid running it automatically -->

```{r setup_2}
# Load packages
library(magrittr)
library(readxl)
library(tidyverse)  # load last to avoid masking by others

# Import data
trials <- read_excel(
  "../../data/interim_data/LargePedsRCT_Finalized_07092020.xlsx",
  sheet = 1
)
```



***

# Rearrange & rename

```{r}
trials %<>% 
  select(nct_id, eligible, everything()) %>% 
  select(
    -sc_category_conditions_draft1,
    -sc_bestdescriptivecondition
  ) %>% 
  rename(
    who_condition_ids = sc_multiplecategoryconditions_GBD_final,
    who_level_three_ids = yellow_category_sc,
    n_sample = enrollment_extracted_publication_sc
  )
```


# Eligibility

```{r}
trials %<>% 
  rename(is_eligible = eligible) %>% 
  mutate(is_eligible = case_when(
    is_eligible == "y" ~ TRUE,
    is_eligible == "n" ~ FALSE,
    is_eligible == "unclear" ~ FALSE,
  ))
```


# WHO

```{r}
trials %<>% 
  mutate(is_who_condition_defined = !is.na(who_condition_ids)) %>% 
  relocate(is_who_condition_defined, .before = who_condition_ids)
```


# Sample size

```{r}
trials %<>% 
  mutate(n_sample = case_when(
    is.na(enrollment_actual) ~ enrollment_estimated,
    status_june23_sc == "Completed" & 
      enrollment_actual == 0 ~ enrollment_estimated,
    TRUE ~ enrollment_actual
  )) %>% 
  relocate(n_sample, .after = enrollment_actual_publication_sc)
```


# Country

## Participants

```{r}
temp <-
  trials %>% 
  select(nct_id, region = country_participants, n_sample) %>% 
  separate_rows(region, sep = "; ") %>%
  mutate_at(vars(region), str_squish) %>%
  mutate_at(vars(region), na_if, "notprovided") %>%
  mutate_at(vars(region), str_remove, ";|\\*") %>%
  mutate_at(vars(region), str_replace, "United States", "USA") %>% 
  mutate_at(vars(region), str_replace, "^United Kin[a-z]+$", "UK") %>% 
  mutate_at(vars(region), str_replace, "^Cz[a-z]+$", "Czech Republic") %>% 
  mutate_at(vars(region), str_replace, "Hong Kong", "China") %>%
  mutate_at(vars(region), str_replace, "The Gambia", "Gambia") %>%
  mutate_at(vars(region), str_replace, "f Congo", "f the Congo") %>% 
  mutate_at(vars(region), str_replace, "Isreal", "Israel") %>% 
  group_by(nct_id) %>% 
  summarise(region = paste(region, collapse = "; "))

trials %<>% 
  full_join(temp) %>% 
  select(-country_participants, country_participants = region) %>% 
  relocate(country_participants, .before = country_collaborators)
```


## Collaborators

```{r}
temp <-
  trials %>% 
  select(nct_id, region = country_collaborators, n_sample) %>% 
  separate_rows(region, sep = "; ") %>%
  mutate_at(vars(region), na_if, "notprovided") %>%
  mutate_at(vars(region), str_remove, ";") %>%
  mutate_at(vars(region), str_replace, "United States", "USA") %>% 
  mutate_at(vars(region), str_replace, "^United Kin[a-z]+$", "UK") %>% 
  mutate_at(vars(region), str_replace, "^Cz[a-z]+$", "Czech Republic") %>% 
  mutate_at(vars(region), str_replace, "Hong Kong", "China") %>%
  mutate_at(vars(region), str_replace, "The Gambia", "Gambia") %>%
  mutate_at(vars(region), str_replace, "f Congo", "f the Congo") %>% 
  group_by(nct_id) %>% 
  summarise(region = paste(region, collapse = "; "))

trials %<>% 
  full_join(temp) %>% 
  select(-country_collaborators, country_collaborators = region) %>% 
  relocate(country_collaborators, .after = country_participants)
```


## Investigators

```{r}
temp <-
  trials %>% 
  select(nct_id, region = country_investigator, n_sample) %>% 
  separate_rows(region, sep = "; ") %>%
  mutate_at(vars(region), na_if, "notprovided") %>%
  mutate_at(vars(region), str_remove, ";") %>%
  mutate_at(vars(region), str_replace, "United States", "USA") %>% 
  mutate_at(vars(region), str_replace, "^United Kin[a-z]+$", "UK") %>% 
  mutate_at(vars(region), str_replace, "^Cz[a-z]+$", "Czech Republic") %>% 
  mutate_at(vars(region), str_replace, "Hong Kong", "China") %>%
  mutate_at(vars(region), str_replace, "The Gambia", "Gambia") %>%
  mutate_at(vars(region), str_replace, "f Congo", "f the Congo") %>% 
  group_by(nct_id) %>% 
  summarise(region = paste(region, collapse = "; "))

trials %<>% 
  full_join(temp) %>% 
  select(-country_investigator, country_investigators = region) %>% 
  relocate(country_investigators, .before = country_participants)
```

# Final

```{r}
glimpse(trials)
```


***


# Save

```{r save}
write_csv(trials, "../../data/tidy_data/trials-who.csv")
```


***


# Documentation {.tabset}

## Session Info

```{r session_info, echo=FALSE}
print(sessionInfo(), locale = F)
```


## References

```{r refs, echo=FALSE}
(.packages()) %>% sort %>% lapply(citation) %>% lapply(c) %>% unique
```
